version: '3.8'
services:
  app1:
    build: .
    container_name: app1
    expose:
      - "8001"
    environment:
      - PORT=8001
    command: uvicorn app:app --host 0.0.0.0 --port 8001 --workers 2

  app2:
    build: .
    container_name: app2
    expose:
      - "8002"
    environment:
      - PORT=8002
    command: uvicorn app:app --host 0.0.0.0 --port 8002 --workers 2

  app3:
    build: .
    container_name: app3
    expose:
      - "8003"
    environment:
      - PORT=8003
    command: uvicorn app:app --host 0.0.0.0 --port 8003 --workers 2

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8888:8888"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
      - app3
